version: '3'

services:
   task-service-classification:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: task-service-classification
    container_name: task-service-classification
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - task-network
networks:
  task-network:
    external: true